version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: gabrielpellegrini/nodejs:8.11.2
    command: nodemon app.js
    tty: true
    stdin_open: true
    container_name: node
    ports:
      - 3050:3000
    volumes:
      - .:/home/app/portal
      - /home/app/portal/node_modules
    networks: 
      - default
  mysql:
    image: gabrielpellegrini/mysql:5.7node
    container_name: mysql_app
    tty: true
    stdin_open: true
    ports: 
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=gabrieric
networks:
  default:
    external:
      name: localNetwork



    